#!/usr/bin/env python3
"""The C# raw layer (plan sections 7 and 12; implementation plan 1.7): api.json to
BwapiC2.Raw/Native.cs, one static class with a [DllImport("bwapi_c2", Cdecl)] per function, a
const int per constant, a [StructLayout(Sequential)] struct per struct, and a Cdecl delegate per
callback. No wrapper classes. Needs only the standard library.

    bindings/csharp/gen.py [--api api.json] [--out bindings/csharp/BwapiC2.Raw/Native.cs]
"""
import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

SCALARS = {
    "int32_t": "int", "int64_t": "long", "uint32_t": "uint", "uint8_t": "byte", "int16_t": "short",
    "double": "double", "bwapi_position": "long", "void*": "IntPtr",
    "const char*": "[MarshalAs(UnmanagedType.LPStr)] string",
    # Output buffers marshal as arrays: the runtime pins them and passes the first element.
    "char*": "byte[]", "int32_t*": "int[]", "double*": "double[]", "int16_t*": "short[]",
    "uint8_t*": "byte[]", "bwapi_position*": "long[]",
}


# A C parameter name that is a C# keyword is spelled with @ (out is the one api.json has today).
CS_KEYWORDS = {"out", "in", "ref", "params", "base", "event", "object", "string", "class", "struct",
               "new", "fixed", "lock", "checked", "unchecked", "default", "operator", "this", "value"}


def cs_name(name):
    return "@" + name if name in CS_KEYWORDS else name


def cstype(c_type, structs, callbacks):
    if c_type in SCALARS:
        return SCALARS[c_type]
    if c_type.startswith("bwapi_") and c_type.endswith("_id"):
        return "int"
    if c_type in callbacks:
        return c_type
    base = c_type.rstrip("*").replace("const ", "").strip()
    if c_type.endswith("*") and base in structs:
        return f"{base}[]"
    raise SystemExit(f"gen.py: no C# mapping for {c_type!r}")


def field_cstype(c_type):
    base, _, count = c_type.partition("[")
    t = SCALARS[base]
    if count:
        return f"[MarshalAs(UnmanagedType.ByValArray, SizeConst = {count.rstrip(']')})] public {t}[]"
    return f"public {t}"


def render(api):
    structs = [s["c_type"] for s in api["structs"]]
    callbacks = {"bwapi_log_callback", "bwapi_error_callback"}
    out = [
        "// GENERATED by bindings/csharp/gen.py from api.json; do not edit. The raw P/Invoke layer of",
        f"// bwapi-c2 {api['abi_version']} (api_json_version {api['api_json_version']}): every constant, every",
        "// struct, every function. No wrapper classes.",
        "using System;",
        "using System.Runtime.InteropServices;",
        "",
        "namespace BwapiC2.Raw",
        "{",
        "    public static class Native",
        "    {",
        '        public const string Library = "bwapi_c2";',
        "        public const int BWAPI_NONE = -1;",
        "",
        "        // Positions: x in the low 32 bits, y in the high 32, two's complement.",
        "        public static int PosX(long p) => unchecked((int)(p & 0xFFFFFFFFL));",
        "        public static int PosY(long p) => unchecked((int)((p >> 32) & 0xFFFFFFFFL));",
        "        public static long PosMake(int x, int y) => unchecked(((long)(uint)y << 32) | (uint)x);",
        "",
    ]
    for fam in api["constants"]:
        out.append(f"        // {fam['family']}" + (f": {fam['cpp']}" if fam["cpp"] else ""))
        for v in fam["values"]:
            out.append(f"        public const int {v['name']} = {v['value']};")
        out.append("")
    out.append("        // Packed position sentinels, from the unpacked halves.")
    for scale in ("POSITION", "WALKPOSITION", "TILEPOSITION"):
        for which in ("INVALID", "NONE", "UNKNOWN", "ORIGIN"):
            out.append(f"        public static readonly long BWAPI_{scale}_{which} = PosMake(BWAPI_{scale}_{which}_X, BWAPI_{scale}_{which}_Y);")
    out.append("")
    out.append("        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]")
    out.append("        public delegate void bwapi_log_callback(int level, IntPtr msg, IntPtr user);")
    out.append("        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]")
    out.append("        public delegate void bwapi_error_callback(int code, IntPtr msg, IntPtr user);")
    out.append("")
    for s in api["structs"]:
        out.append("        [StructLayout(LayoutKind.Sequential)]")
        out.append(f"        public struct {s['c_type']}")
        out.append("        {")
        for f in s["fields"]:
            out.append(f"            {field_cstype(f['c_type'])} {f['name']};")
        out.append("        }")
        out.append("")
    for fn in api["functions"]:
        params = ", ".join(f"{cstype(p['c_type'], structs, callbacks)} {cs_name(p['name'])}" for p in fn["params"])
        ret = "void" if fn["returns"]["c_type"] == "void" else cstype(fn["returns"]["c_type"], structs, callbacks)
        out.append(f"        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, EntryPoint = \"{fn['c']}\")]")
        out.append(f"        public static extern {ret} {fn['c']}({params});")
        out.append("")
    out.append("    }")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--api", default=os.path.join(REPO, "api.json"))
    ap.add_argument("--out", default=os.path.join(HERE, "BwapiC2.Raw", "Native.cs"))
    args = ap.parse_args()
    with open(args.api, encoding="utf-8") as f:
        api = json.load(f)
    if api.get("api_json_version") != 1:
        raise SystemExit(f"gen.py: api_json_version {api.get('api_json_version')} is not the 1 this generator reads")
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(render(api))
    print(f"wrote {os.path.relpath(args.out, REPO)}: {len(api['functions'])} functions, "
          f"{sum(len(c['values']) for c in api['constants'])} constants, {len(api['structs'])} structs")


if __name__ == "__main__":
    main()
