#!/usr/bin/env python3
"""The Python raw layer (plan sections 7 and 12; implementation plan 1.7): api.json to
bwapi_c2/_raw.py, a ctypes module with the library loaded, argtypes and restype on every
function, every constant as a module attribute, every struct as a ctypes.Structure, and the
three position macros as functions. No wrapper classes: the idiomatic package lives in its own
repository (plan section 7). Needs only the standard library.

    bindings/python/gen.py [--api api.json] [--out bindings/python/bwapi_c2/_raw.py]

The generated module loads the library named by BWAPI_C2_LIBRARY, else bwapi_c2.dll /
libbwapi_c2.so / libbwapi_c2.dylib from the loader's search path.
"""
import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

SCALARS = {
    "int32_t": "ctypes.c_int32", "int64_t": "ctypes.c_int64", "uint32_t": "ctypes.c_uint32",
    "uint8_t": "ctypes.c_uint8", "int16_t": "ctypes.c_int16", "double": "ctypes.c_double",
    "bwapi_position": "ctypes.c_int64", "void*": "ctypes.c_void_p", "const char*": "ctypes.c_char_p",
    # An output buffer is a pointer to writable chars, never c_char_p (which would copy).
    "char*": "ctypes.POINTER(ctypes.c_char)",
    "int32_t*": "ctypes.POINTER(ctypes.c_int32)", "double*": "ctypes.POINTER(ctypes.c_double)",
    "int16_t*": "ctypes.POINTER(ctypes.c_int16)", "uint8_t*": "ctypes.POINTER(ctypes.c_uint8)",
    "bwapi_position*": "ctypes.POINTER(ctypes.c_int64)",
}


def ctype(c_type, structs, callbacks):
    if c_type in SCALARS:
        return SCALARS[c_type]
    if c_type.startswith("bwapi_") and c_type.endswith("_id"):
        return "ctypes.c_int32"
    if c_type in callbacks:
        return c_type
    base = c_type.rstrip("*").replace("const ", "").strip()
    if c_type.endswith("*") and base in structs:
        return f"ctypes.POINTER({base})"
    raise SystemExit(f"gen.py: no ctypes mapping for {c_type!r}")


def field_ctype(c_type):
    base, _, count = c_type.partition("[")
    t = SCALARS[base]
    return f"{t} * {count.rstrip(']')}" if count else t


def render(api):
    structs = [s["c_type"] for s in api["structs"]]
    callbacks = {"bwapi_log_callback", "bwapi_error_callback"}
    out = [
        "# GENERATED by bindings/python/gen.py from api.json; do not edit. The raw ctypes layer of",
        f"# bwapi-c2 {api['abi_version']} (api_json_version {api['api_json_version']}): the library, every",
        "# constant, every struct, argtypes and restype on every function. No wrapper classes.",
        "import ctypes",
        "import os",
        "import sys",
        "",
        "",
        "def _load():",
        '    path = os.environ.get("BWAPI_C2_LIBRARY")',
        "    if not path:",
        '        path = {"win32": "bwapi_c2.dll", "darwin": "libbwapi_c2.dylib"}.get(sys.platform, "libbwapi_c2.so")',
        "    return ctypes.CDLL(path)",
        "",
        "",
        "lib = _load()",
        "",
        "# ---- positions: x in the low 32 bits, y in the high 32, two's complement ----",
        "",
        "",
        "def pos_x(p):",
        "    return ctypes.c_int32(p & 0xFFFFFFFF).value",
        "",
        "",
        "def pos_y(p):",
        "    return ctypes.c_int32((p >> 32) & 0xFFFFFFFF).value",
        "",
        "",
        "def pos_make(x, y):",
        "    return ctypes.c_int64(((y & 0xFFFFFFFF) << 32) | (x & 0xFFFFFFFF)).value",
        "",
        "",
        "BWAPI_NONE = -1",
        "",
    ]
    for fam in api["constants"]:
        out.append(f"# ---- {fam['family']}" + (f": {fam['cpp']}" if fam["cpp"] else "") + " ----")
        for v in fam["values"]:
            out.append(f"{v['name']} = {v['value']}")
        out.append("")
    # The packed sentinels, from the unpacked halves.
    out.append("# ---- packed position sentinels ----")
    for scale in ("POSITION", "WALKPOSITION", "TILEPOSITION"):
        for which in ("INVALID", "NONE", "UNKNOWN", "ORIGIN"):
            out.append(f"BWAPI_{scale}_{which} = pos_make(BWAPI_{scale}_{which}_X, BWAPI_{scale}_{which}_Y)")
    out.append("")
    out.append("# ---- callbacks ----")
    out.append("bwapi_log_callback = ctypes.CFUNCTYPE(None, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)")
    out.append("bwapi_error_callback = ctypes.CFUNCTYPE(None, ctypes.c_int32, ctypes.c_char_p, ctypes.c_void_p)")
    out.append("")
    out.append("# ---- structs: every one begins with size (the caller's stride in, the bytes filled out) ----")
    for s in api["structs"]:
        out.append("")
        out.append("")
        out.append(f"class {s['c_type']}(ctypes.Structure):")
        out.append(f"    _fields_ = [")
        for f in s["fields"]:
            out.append(f'        ("{f["name"]}", {field_ctype(f["c_type"])}),')
        out.append("    ]")
    out.append("")
    out.append("")
    out.append("# ---- functions ----")
    for fn in api["functions"]:
        args = ", ".join(ctype(p["c_type"], structs, callbacks) for p in fn["params"])
        ret = "None" if fn["returns"]["c_type"] == "void" else ctype(fn["returns"]["c_type"], structs, callbacks)
        out.append(f"{fn['c']} = lib.{fn['c']}")
        out.append(f"{fn['c']}.argtypes = [{args}]")
        out.append(f"{fn['c']}.restype = {ret}")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--api", default=os.path.join(REPO, "api.json"))
    ap.add_argument("--out", default=os.path.join(HERE, "bwapi_c2", "_raw.py"))
    args = ap.parse_args()
    with open(args.api, encoding="utf-8") as f:
        api = json.load(f)
    if api.get("api_json_version") != 1:
        raise SystemExit(f"gen.py: api_json_version {api.get('api_json_version')} is not the 1 this generator reads")
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(render(api))
    print(f"wrote {os.path.relpath(args.out, REPO)}: {len(api['functions'])} functions, "
          f"{sum(len(c['values']) for c in api['constants'])} constants, {len(api['structs'])} structs")


if __name__ == "__main__":
    main()
