#!/usr/bin/env python3
"""The .def emitter (plan sections 4 and 9; implementation plan 1.4): every export in the spec,
sorted by name, no ordinals, to bwapi_c2.def. The golden symbol artifact: MSVC links the DLL
from it, and tests/exports diffs the built library's export table against it on every
platform, so a definition the spec does not know about, or a spec entry nothing defines, is a
test failure.

    tools/abi/emit_def.py            # writes bwapi_c2.def
    tools/abi/emit_def.py --check    # exits 1 if it would change
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import abispec  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
DEF = os.path.join(REPO, "bwapi_c2.def")

HEADER = """\
; Exports of bwapi_c2.dll (plan section 4). Names only, never ordinals: binding is by name, so a
; reordered list can never silently rebind a consumer. GENERATED by tools/abi/emit_def.py from
; tools/abi/spec/; do not edit. CI fails on any diff (implementation plan rule 2), and
; tests/exports diffs the built library's export table against this file.
LIBRARY bwapi_c2
EXPORTS
"""


def render(spec):
    names = sorted(e["c"] for _, e in spec.exports())
    return HEADER + "".join(f"    {n}\n" for n in names)


def main():
    text = render(abispec.Spec())
    old = open(DEF, encoding="utf-8").read() if os.path.exists(DEF) else None
    if "--check" in sys.argv:
        if old != text:
            print("emit_def: bwapi_c2.def is out of date", file=sys.stderr)
            sys.exit(1)
        return
    if old != text:
        with open(DEF, "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote bwapi_c2.def")


if __name__ == "__main__":
    main()
