/* bwapi_c2.h -- the BWAPI half of bwapi-c2: lifecycle, versions, the error channel, the two
 * callbacks, the client, and every wrapper over BWAPI::Game, Unit, Player, Force and Region.
 *
 * GENERATED by tools/abi/emit_header.py from tools/abi/spec/ and tools/abi/templates/; do not
 * edit. A change to the ABI is a change to a spec file (docs/spec-format.md), and CI fails when
 * regenerating produces a diff. The one-line comment above each declaration is the first
 * sentence of its reference entry; the whole entry, with the parameters, the neutral value and
 * when it latches, is on the site under /reference/.
 *
 * The conventions are stated once, at the top of bwapi_c2_types.h, and hold for every
 * declaration here. The protocol is section 4.1 of docs/c-abi-plan.md:
 *
 *     while (!bwapi_client_connect()) sleep(1000);
 *     for (;;) {
 *       while (!bwapi_game_is_in_game()) { bwapi_client_update(); if (!bwapi_client_is_connected()) goto reconnect; }
 *       while (bwapi_game_is_in_game()) {
 *         bwapi_clear_last_error();
 *         ... poll events, take snapshots, issue commands ...
 *         bwapi_client_update();                  -- blocks on the pipe
 *         if (!bwapi_client_is_connected()) break;
 *       }
 *     }
 *
 * The two error channels have different lifetimes. bwapi_last_error() is sticky: it latches
 * the FIRST error since the last clear and is never cleared implicitly; successful calls do
 * not touch it and reading does not clear it. Clear it at the top of the frame, check it
 * before update(). BWAPI's own Game::getLastError() is per call and comes back through
 * bwapi_game_get_last_error().
 */
#ifndef BWAPI_C2_H
#define BWAPI_C2_H

#include "bwapi_c2_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ---- the ABI itself and the client: versions, the error channel, callbacks, lifecycle ------------ */

/* The ABI's own version, written to the three out-params; any of them may be NULL and is then
 * skipped. */
BWAPI_C2_API void BWAPI_C2_CALL bwapi_abi_version(int32_t* major, int32_t* minor, int32_t* patch) BWAPI_C2_NOEXCEPT;
/* The ABI's own version as "major.minor.patch". */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_abi_version_string(char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT;
/* BWAPI::CLIENT_VERSION of the pinned BWAPI (10003 today). */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_client_version(void) BWAPI_C2_NOEXCEPT;
/* SVN_REV of the pinned BWAPI, from upstream's own revision generator (plan section 10.3). */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_revision(void) BWAPI_C2_NOEXCEPT;
/* 1 when the pinned BWAPI was built with BUILD_DEBUG, 0 otherwise. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_is_debug(void) BWAPI_C2_NOEXCEPT;
/* The BWAPI_ERR_* code latched by the first failing call since the last
 * bwapi_clear_last_error(), or BWAPI_ERR_NONE. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_last_error(void) BWAPI_C2_NOEXCEPT;
/* The message that came with the latched code: a BWEM::Exception's what(), the two unit ids of
 * an overlap, the name of the export a bad handle was passed to. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_last_error_message(char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT;
/* Resets the sticky error channel to BWAPI_ERR_NONE and clears its message. */
BWAPI_C2_API void BWAPI_C2_CALL bwapi_clear_last_error(void) BWAPI_C2_NOEXCEPT;
/* Installs where the ABI's own diagnostics go, at BWAPI_LOG_* levels, with the user pointer
 * handed back on every call. */
BWAPI_C2_API void BWAPI_C2_CALL bwapi_set_log_callback(bwapi_log_callback cb, void* user) BWAPI_C2_NOEXCEPT;
/* Installs a callback invoked at the moment an error is latched, with the code, its message and
 * the user pointer, so a wrapper can raise at the failing call rather than poll. */
BWAPI_C2_API void BWAPI_C2_CALL bwapi_set_error_callback(bwapi_error_callback cb, void* user) BWAPI_C2_NOEXCEPT;
/* Connects to a running BWAPI server over its shared memory and pipe. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_client_connect(void) BWAPI_C2_NOEXCEPT;
/* Ends the frame and BLOCKS on the pipe until the server hands back the next one. */
BWAPI_C2_API void BWAPI_C2_CALL bwapi_client_update(void) BWAPI_C2_NOEXCEPT;
/* Tears down BWEM first, because its map points into the game data, then the client. */
BWAPI_C2_API void BWAPI_C2_CALL bwapi_client_disconnect(void) BWAPI_C2_NOEXCEPT;
/* 1 while connected. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_client_is_connected(void) BWAPI_C2_NOEXCEPT;

/* ---- Player -------------------------------------------------------------------------------------- */

/* The player's id, which is the handle itself: 0..11, the slot in the game's player table. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_id(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The player's name, as the game reports it. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_name(bwapi_player_id player_id, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT;
/* The ids of every unit the player owns, incomplete units included, ascending. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_units(bwapi_player_id player_id, int32_t* out, int32_t cap) BWAPI_C2_NOEXCEPT;
/* The player's race. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_race(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The player's controller type, a BWAPI_PLAYERTYPE_* value. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_type(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The id of the force (team) the player belongs to. */
BWAPI_C2_API bwapi_force_id BWAPI_C2_CALL bwapi_player_get_force(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* 1 when the player is allied with the other player. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_ally(bwapi_player_id player_id, bwapi_player_id other_id) BWAPI_C2_NOEXCEPT;
/* 1 when the player is at war with the other player. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_enemy(bwapi_player_id player_id, bwapi_player_id other_id) BWAPI_C2_NOEXCEPT;
/* 1 when this is the neutral player, which owns the minerals, geysers and critters. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_neutral(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The player's starting location in tile coordinates. */
BWAPI_C2_API bwapi_position BWAPI_C2_CALL bwapi_player_get_start_location(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* 1 when the player has achieved victory. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_victorious(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* 1 when the player has been defeated. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_defeated(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* 1 when the player has left the game. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_left_game(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The player's current minerals. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The player's current vespene gas. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The minerals the player has gathered since the game began, starting minerals included. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_gathered_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The vespene gas the player has gathered since the game began, starting gas included. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_gathered_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The minerals the player has spent on repairs since the game began. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_repaired_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The vespene gas the player has spent on repairs since the game began. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_repaired_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The minerals the player has recovered by cancelling units and structures. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_refunded_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The vespene gas the player has recovered by cancelling units and structures. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_refunded_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The minerals the player has spent, repairs excluded. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_spent_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The vespene gas the player has spent, repairs excluded. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_spent_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The supply available to the player for the given race, or for the player's own race when race
 * is BWAPI_RACE_NONE. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_supply_total(bwapi_player_id player_id, int32_t race) BWAPI_C2_NOEXCEPT;
/* The supply the player is using for the given race, or for the player's own race when race is
 * BWAPI_RACE_NONE. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_supply_used(bwapi_player_id player_id, int32_t race) BWAPI_C2_NOEXCEPT;
/* How many units of the type the player has, incomplete ones included; BWAPI_UNIT_ALL_UNITS
 * counts every type. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_all_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* How many units of the type the player has that are strictly visible to this bot, even when
 * information on the player is unrestricted; BWAPI_UNIT_ALL_UNITS counts every type. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_visible_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* How many completed units of the type the player has; BWAPI_UNIT_ALL_UNITS counts every type. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_completed_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* How many incomplete units of the type the player has, which is the all count less the
 * completed count; BWAPI_UNIT_ALL_UNITS counts every type. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_incomplete_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* How many of the player's units of the type have died; BWAPI_UNIT_ALL_UNITS counts every type. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_dead_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* How many units of the type the player has killed; BWAPI_UNIT_ALL_UNITS counts every type. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_killed_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* The level the player has attained for the upgrade, 0 when none. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_upgrade_level(bwapi_player_id player_id, int32_t upgrade) BWAPI_C2_NOEXCEPT;
/* 1 when the player has researched the technology. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_has_researched(bwapi_player_id player_id, int32_t tech) BWAPI_C2_NOEXCEPT;
/* 1 while the player is researching the technology. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_researching(bwapi_player_id player_id, int32_t tech) BWAPI_C2_NOEXCEPT;
/* 1 while the player is upgrading the upgrade. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_upgrading(bwapi_player_id player_id, int32_t upgrade) BWAPI_C2_NOEXCEPT;
/* The player's colour as a palette index, the value the drawing functions take. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_color(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The control character that switches text to the player's colour, as a BWAPI_TEXT_* value; put
 * it in a string passed to the drawing and text functions. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_text_color(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The maximum energy a unit of the type has for this player, the player's energy upgrades
 * included. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_max_energy(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* The top speed of a unit of the type for this player, the player's speed upgrades included. */
BWAPI_C2_API double BWAPI_C2_CALL bwapi_player_top_speed(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* The maximum range of the weapon for this player, the player's range upgrades included. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_weapon_max_range(bwapi_player_id player_id, int32_t weapon) BWAPI_C2_NOEXCEPT;
/* The sight range of a unit of the type for this player, the player's sight upgrades included. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_sight_range(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* The ground weapon cooldown of a unit of the type for this player, the player's attack speed
 * upgrades included. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_weapon_damage_cooldown(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* The armour a unit of the type has for this player, upgrades included. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_armor(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* The damage the weapon deals for this player, upgrades included. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_damage(bwapi_player_id player_id, int32_t weapon) BWAPI_C2_NOEXCEPT;
/* The player's unit score, as on the end-game score screen. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_unit_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The player's kill score, as on the end-game score screen. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_kill_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The player's building score, as on the end-game score screen. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_building_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The player's razing score, as on the end-game score screen. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_razing_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The player's custom score, which map triggers set. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_custom_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* 1 when the player is an observer, typically in a use-map-settings observer game. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_observer(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT;
/* The highest level of the upgrade available to this player, which map settings may lower from
 * the type's own maximum. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_max_upgrade_level(bwapi_player_id player_id, int32_t upgrade) BWAPI_C2_NOEXCEPT;
/* 1 when the player is allowed to research the technology under the map's settings. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_research_available(bwapi_player_id player_id, int32_t tech) BWAPI_C2_NOEXCEPT;
/* 1 when the player is allowed to create units of the type under the map's settings. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_unit_available(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT;
/* 1 when the player has at least amount completed units of the type, counting the equivalents
 * BWAPI counts: a Lair or Hive for a Hatchery, a Hive for a Lair, a sieged tank for an unsieged
 * one, and both Templar and Archon forms. */
BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_has_unit_type_requirement(bwapi_player_id player_id, int32_t unit_type, int32_t amount) BWAPI_C2_NOEXCEPT;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* BWAPI_C2_H */
