// GENERATED by tools/abi/emit_source.py from tools/abi/spec/bulk.yaml; do not edit.
// The boundary every wrapper shares is abi_internal.h; the conversions are docs/spec-format.md
// section 1.4. A change to the ABI is a change to the spec file.
#include "abi_internal.h"

#include <BWAPI/Client.h>
#include <bwem.h>

#include <type_traits>
#include <utility>

using namespace bwapi_c2;

// Every body: and source: entry names the C++ declaration it stands for; these fail the build
// when a pin bump removes or reshapes one (plan section 9).
static_assert(sizeof(&BWAPI::UnitType::requiredUnits) > 0, "spec/bulk.yaml bwapi_unittype_required_units_table: UnitType::requiredUnits not found");

extern "C" {

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_table(bwapi_unittype_row* out, int32_t cap, int32_t stride) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    auto body = [&] {
      const int32_t total = id_count<BWAPI::UnitType>();
      return write_rows(out, cap, stride, total, [](bwapi_unittype_row& row, int32_t id) {
        const BWAPI::UnitType t(id);
        row.id = id;
        row.get_race = (t.getRace()).getID();
        row.required_tech = (t.requiredTech()).getID();
        row.cloaking_tech = (t.cloakingTech()).getID();
        row.armor_upgrade = (t.armorUpgrade()).getID();
        row.max_hit_points = static_cast<int32_t>(t.maxHitPoints());
        row.max_shields = static_cast<int32_t>(t.maxShields());
        row.max_energy = static_cast<int32_t>(t.maxEnergy());
        row.armor = static_cast<int32_t>(t.armor());
        row.mineral_price = static_cast<int32_t>(t.mineralPrice());
        row.gas_price = static_cast<int32_t>(t.gasPrice());
        row.build_time = static_cast<int32_t>(t.buildTime());
        row.supply_required = static_cast<int32_t>(t.supplyRequired());
        row.supply_provided = static_cast<int32_t>(t.supplyProvided());
        row.space_required = static_cast<int32_t>(t.spaceRequired());
        row.space_provided = static_cast<int32_t>(t.spaceProvided());
        row.build_score = static_cast<int32_t>(t.buildScore());
        row.destroy_score = static_cast<int32_t>(t.destroyScore());
        row.size_type = (t.size()).getID();
        row.tile_width = static_cast<int32_t>(t.tileWidth());
        row.tile_height = static_cast<int32_t>(t.tileHeight());
        row.dimension_left = static_cast<int32_t>(t.dimensionLeft());
        row.dimension_up = static_cast<int32_t>(t.dimensionUp());
        row.dimension_right = static_cast<int32_t>(t.dimensionRight());
        row.dimension_down = static_cast<int32_t>(t.dimensionDown());
        row.width = static_cast<int32_t>(t.width());
        row.height = static_cast<int32_t>(t.height());
        row.seek_range = static_cast<int32_t>(t.seekRange());
        row.sight_range = static_cast<int32_t>(t.sightRange());
        row.ground_weapon = (t.groundWeapon()).getID();
        row.max_ground_hits = static_cast<int32_t>(t.maxGroundHits());
        row.air_weapon = (t.airWeapon()).getID();
        row.max_air_hits = static_cast<int32_t>(t.maxAirHits());
        row.top_speed = static_cast<double>(t.topSpeed());
        row.acceleration = static_cast<int32_t>(t.acceleration());
        row.halt_distance = static_cast<int32_t>(t.haltDistance());
        row.turn_radius = static_cast<int32_t>(t.turnRadius());
        row.can_produce = (t.canProduce()) ? 1 : 0;
        row.can_attack = (t.canAttack()) ? 1 : 0;
        row.can_move = (t.canMove()) ? 1 : 0;
        row.is_flyer = (t.isFlyer()) ? 1 : 0;
        row.regenerates_hp = (t.regeneratesHP()) ? 1 : 0;
        row.is_spellcaster = (t.isSpellcaster()) ? 1 : 0;
        row.has_permanent_cloak = (t.hasPermanentCloak()) ? 1 : 0;
        row.is_invincible = (t.isInvincible()) ? 1 : 0;
        row.is_organic = (t.isOrganic()) ? 1 : 0;
        row.is_mechanical = (t.isMechanical()) ? 1 : 0;
        row.is_robotic = (t.isRobotic()) ? 1 : 0;
        row.is_detector = (t.isDetector()) ? 1 : 0;
        row.is_resource_container = (t.isResourceContainer()) ? 1 : 0;
        row.is_resource_depot = (t.isResourceDepot()) ? 1 : 0;
        row.is_refinery = (t.isRefinery()) ? 1 : 0;
        row.is_worker = (t.isWorker()) ? 1 : 0;
        row.requires_psi = (t.requiresPsi()) ? 1 : 0;
        row.requires_creep = (t.requiresCreep()) ? 1 : 0;
        row.is_two_units_in_one_egg = (t.isTwoUnitsInOneEgg()) ? 1 : 0;
        row.is_burrowable = (t.isBurrowable()) ? 1 : 0;
        row.is_cloakable = (t.isCloakable()) ? 1 : 0;
        row.is_building = (t.isBuilding()) ? 1 : 0;
        row.is_addon = (t.isAddon()) ? 1 : 0;
        row.is_flying_building = (t.isFlyingBuilding()) ? 1 : 0;
        row.is_neutral = (t.isNeutral()) ? 1 : 0;
        row.is_hero = (t.isHero()) ? 1 : 0;
        row.is_powerup = (t.isPowerup()) ? 1 : 0;
        row.is_beacon = (t.isBeacon()) ? 1 : 0;
        row.is_flag_beacon = (t.isFlagBeacon()) ? 1 : 0;
        row.is_special_building = (t.isSpecialBuilding()) ? 1 : 0;
        row.is_spell = (t.isSpell()) ? 1 : 0;
        row.produces_creep = (t.producesCreep()) ? 1 : 0;
        row.produces_larva = (t.producesLarva()) ? 1 : 0;
        row.is_mineral_field = (t.isMineralField()) ? 1 : 0;
        row.is_critter = (t.isCritter()) ? 1 : 0;
        row.can_build_addon = (t.canBuildAddon()) ? 1 : 0;
      });
    };
    return body();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_table(bwapi_weapontype_row* out, int32_t cap, int32_t stride) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    auto body = [&] {
      const int32_t total = id_count<BWAPI::WeaponType>();
      return write_rows(out, cap, stride, total, [](bwapi_weapontype_row& row, int32_t id) {
        const BWAPI::WeaponType t(id);
        row.id = id;
        row.get_tech = (t.getTech()).getID();
        row.what_uses = (t.whatUses()).getID();
        row.damage_amount = static_cast<int32_t>(t.damageAmount());
        row.damage_bonus = static_cast<int32_t>(t.damageBonus());
        row.damage_cooldown = static_cast<int32_t>(t.damageCooldown());
        row.damage_factor = static_cast<int32_t>(t.damageFactor());
        row.upgrade_type = (t.upgradeType()).getID();
        row.damage_type = (t.damageType()).getID();
        row.explosion_type = (t.explosionType()).getID();
        row.min_range = static_cast<int32_t>(t.minRange());
        row.max_range = static_cast<int32_t>(t.maxRange());
        row.inner_splash_radius = static_cast<int32_t>(t.innerSplashRadius());
        row.median_splash_radius = static_cast<int32_t>(t.medianSplashRadius());
        row.outer_splash_radius = static_cast<int32_t>(t.outerSplashRadius());
        row.targets_air = (t.targetsAir()) ? 1 : 0;
        row.targets_ground = (t.targetsGround()) ? 1 : 0;
        row.targets_mechanical = (t.targetsMechanical()) ? 1 : 0;
        row.targets_organic = (t.targetsOrganic()) ? 1 : 0;
        row.targets_non_building = (t.targetsNonBuilding()) ? 1 : 0;
        row.targets_non_robotic = (t.targetsNonRobotic()) ? 1 : 0;
        row.targets_terrain = (t.targetsTerrain()) ? 1 : 0;
        row.targets_org_or_mech = (t.targetsOrgOrMech()) ? 1 : 0;
        row.targets_own = (t.targetsOwn()) ? 1 : 0;
      });
    };
    return body();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_table(bwapi_techtype_row* out, int32_t cap, int32_t stride) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    auto body = [&] {
      const int32_t total = id_count<BWAPI::TechType>();
      return write_rows(out, cap, stride, total, [](bwapi_techtype_row& row, int32_t id) {
        const BWAPI::TechType t(id);
        row.id = id;
        row.get_race = (t.getRace()).getID();
        row.mineral_price = static_cast<int32_t>(t.mineralPrice());
        row.gas_price = static_cast<int32_t>(t.gasPrice());
        row.research_time = static_cast<int32_t>(t.researchTime());
        row.energy_cost = static_cast<int32_t>(t.energyCost());
        row.what_researches = (t.whatResearches()).getID();
        row.get_weapon = (t.getWeapon()).getID();
        row.targets_unit = (t.targetsUnit()) ? 1 : 0;
        row.targets_position = (t.targetsPosition()) ? 1 : 0;
        row.get_order = (t.getOrder()).getID();
        row.required_unit = (t.requiredUnit()).getID();
      });
    };
    return body();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_table(bwapi_upgradetype_row* out, int32_t cap, int32_t stride) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    auto body = [&] {
      const int32_t total = id_count<BWAPI::UpgradeType>();
      return write_rows(out, cap, stride, total, [](bwapi_upgradetype_row& row, int32_t id) {
        const BWAPI::UpgradeType t(id);
        row.id = id;
        row.get_race = (t.getRace()).getID();
        row.mineral_price_factor = static_cast<int32_t>(t.mineralPriceFactor());
        row.gas_price_factor = static_cast<int32_t>(t.gasPriceFactor());
        row.upgrade_time_factor = static_cast<int32_t>(t.upgradeTimeFactor());
        row.max_repeats = static_cast<int32_t>(t.maxRepeats());
        row.what_upgrades = (t.whatUpgrades()).getID();
      });
    };
    return body();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_race_table(bwapi_race_row* out, int32_t cap, int32_t stride) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    auto body = [&] {
      const int32_t total = id_count<BWAPI::Race>();
      return write_rows(out, cap, stride, total, [](bwapi_race_row& row, int32_t id) {
        const BWAPI::Race t(id);
        row.id = id;
        row.get_worker = (t.getWorker()).getID();
        row.get_resource_depot = (t.getResourceDepot()).getID();
        row.get_refinery = (t.getRefinery()).getID();
        row.get_transport = (t.getTransport()).getID();
        row.get_supply_provider = (t.getSupplyProvider()).getID();
      });
    };
    return body();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_playertype_table(bwapi_playertype_row* out, int32_t cap, int32_t stride) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    auto body = [&] {
      const int32_t total = id_count<BWAPI::PlayerType>();
      return write_rows(out, cap, stride, total, [](bwapi_playertype_row& row, int32_t id) {
        const BWAPI::PlayerType t(id);
        row.id = id;
        row.is_lobby_type = (t.isLobbyType()) ? 1 : 0;
        row.is_game_type = (t.isGameType()) ? 1 : 0;
      });
    };
    return body();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_color_table(bwapi_color_row* out, int32_t cap, int32_t stride) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    auto body = [&] {
      const int32_t total = id_count<BWAPI::Color>();
      return write_rows(out, cap, stride, total, [](bwapi_color_row& row, int32_t id) {
        const BWAPI::Color t(id);
        row.id = id;
        row.red = static_cast<int32_t>(t.red());
        row.green = static_cast<int32_t>(t.green());
        row.blue = static_cast<int32_t>(t.blue());
      });
    };
    return body();
  });
}

}  // extern "C"
