// GENERATED by tools/abi/emit_source.py from tools/abi/spec/game.yaml; do not edit.
// The boundary every wrapper shares is abi_internal.h; the conversions are docs/spec-format.md
// section 1.4. A change to the ABI is a change to the spec file.
#include "abi_internal.h"

#include <BWAPI/Client.h>
#include <bwem.h>

#include <type_traits>
#include <utility>

using namespace bwapi_c2;

// Every body: and source: entry names the C++ declaration it stands for; these fail the build
// when a pin bump removes or reshapes one (plan section 9).
static_assert(sizeof(&BWAPI::Game::getEvents) > 0, "spec/game.yaml bwapi_game_event_count: Game::getEvents not found");
static_assert(sizeof(&BWAPI::Game::getEvents) > 0, "spec/game.yaml bwapi_game_get_events: Game::getEvents not found");
static_assert(sizeof(&BWAPI::Event::getText) > 0, "spec/game.yaml bwapi_game_event_text: Event::getText not found");

// Every export in this file is hand-written (source:); nothing to generate.
