// GENERATED by tools/abi/emit_source.py from tools/abi/spec/player.yaml; do not edit.
// The boundary every wrapper shares is abi_internal.h; the conversions are docs/spec-format.md
// section 1.4. A change to the ABI is a change to the spec file.
#include "abi_internal.h"

#include <BWAPI/Client.h>
#include <bwem.h>

#include <type_traits>
#include <utility>

using namespace bwapi_c2;

extern "C" {

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_id(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_id")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_id");
    if (!self) return 0;
    return static_cast<int32_t>(self->getID());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_name(bwapi_player_id player_id, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    if (!game_ready("bwapi_player_get_name")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_name");
    if (!self) return 0;
    return write_string(buf, buf_len, self->getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_units(bwapi_player_id player_id, int32_t* out, int32_t cap) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    if (!game_ready("bwapi_player_get_units")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_units");
    if (!self) return 0;
    return write_ids(out, cap, self->getUnits());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_race(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::Race(-1).getID(), [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_race")) return BWAPI::Race(-1).getID();
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_race");
    if (!self) return BWAPI::Race(-1).getID();
    return (self->getRace()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_type(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::PlayerType(-1).getID(), [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_type")) return BWAPI::PlayerType(-1).getID();
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_type");
    if (!self) return BWAPI::PlayerType(-1).getID();
    return (self->getType()).getID();
  });
}

BWAPI_C2_API bwapi_force_id BWAPI_C2_CALL bwapi_player_get_force(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<bwapi_force_id>(BWAPI_NONE, [&]() -> bwapi_force_id {
    if (!game_ready("bwapi_player_get_force")) return BWAPI_NONE;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_force");
    if (!self) return BWAPI_NONE;
    return id_of(self->getForce());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_ally(bwapi_player_id player_id, bwapi_player_id other_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_ally")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_ally");
    if (!self) return 0;
    BWAPI::Player other = resolve_player(other_id, "bwapi_player_is_ally");
    if (!other) return 0;
    return (self->isAlly(other)) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_enemy(bwapi_player_id player_id, bwapi_player_id other_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_enemy")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_enemy");
    if (!self) return 0;
    BWAPI::Player other = resolve_player(other_id, "bwapi_player_is_enemy");
    if (!other) return 0;
    return (self->isEnemy(other)) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_neutral(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_neutral")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_neutral");
    if (!self) return 0;
    return (self->isNeutral()) ? 1 : 0;
  });
}

BWAPI_C2_API bwapi_position BWAPI_C2_CALL bwapi_player_get_start_location(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<bwapi_position>(BWAPI_POSITION_NONE, [&]() -> bwapi_position {
    if (!game_ready("bwapi_player_get_start_location")) return BWAPI_POSITION_NONE;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_start_location");
    if (!self) return BWAPI_POSITION_NONE;
    return pack(self->getStartLocation());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_victorious(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_victorious")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_victorious");
    if (!self) return 0;
    return (self->isVictorious()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_defeated(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_defeated")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_defeated");
    if (!self) return 0;
    return (self->isDefeated()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_left_game(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_left_game")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_left_game");
    if (!self) return 0;
    return (self->leftGame()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_minerals")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_minerals");
    if (!self) return 0;
    return static_cast<int32_t>(self->minerals());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_gas")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_gas");
    if (!self) return 0;
    return static_cast<int32_t>(self->gas());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_gathered_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_gathered_minerals")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_gathered_minerals");
    if (!self) return 0;
    return static_cast<int32_t>(self->gatheredMinerals());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_gathered_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_gathered_gas")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_gathered_gas");
    if (!self) return 0;
    return static_cast<int32_t>(self->gatheredGas());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_repaired_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_repaired_minerals")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_repaired_minerals");
    if (!self) return 0;
    return static_cast<int32_t>(self->repairedMinerals());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_repaired_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_repaired_gas")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_repaired_gas");
    if (!self) return 0;
    return static_cast<int32_t>(self->repairedGas());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_refunded_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_refunded_minerals")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_refunded_minerals");
    if (!self) return 0;
    return static_cast<int32_t>(self->refundedMinerals());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_refunded_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_refunded_gas")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_refunded_gas");
    if (!self) return 0;
    return static_cast<int32_t>(self->refundedGas());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_spent_minerals(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_spent_minerals")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_spent_minerals");
    if (!self) return 0;
    return static_cast<int32_t>(self->spentMinerals());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_spent_gas(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_spent_gas")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_spent_gas");
    if (!self) return 0;
    return static_cast<int32_t>(self->spentGas());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_supply_total(bwapi_player_id player_id, int32_t race) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_supply_total")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_supply_total");
    if (!self) return 0;
    return static_cast<int32_t>(self->supplyTotal(BWAPI::Race(race)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_supply_used(bwapi_player_id player_id, int32_t race) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_supply_used")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_supply_used");
    if (!self) return 0;
    return static_cast<int32_t>(self->supplyUsed(BWAPI::Race(race)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_all_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_all_unit_count")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_all_unit_count");
    if (!self) return 0;
    return static_cast<int32_t>(self->allUnitCount(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_visible_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_visible_unit_count")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_visible_unit_count");
    if (!self) return 0;
    return static_cast<int32_t>(self->visibleUnitCount(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_completed_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_completed_unit_count")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_completed_unit_count");
    if (!self) return 0;
    return static_cast<int32_t>(self->completedUnitCount(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_incomplete_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_incomplete_unit_count")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_incomplete_unit_count");
    if (!self) return 0;
    return static_cast<int32_t>(self->incompleteUnitCount(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_dead_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_dead_unit_count")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_dead_unit_count");
    if (!self) return 0;
    return static_cast<int32_t>(self->deadUnitCount(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_killed_unit_count(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_killed_unit_count")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_killed_unit_count");
    if (!self) return 0;
    return static_cast<int32_t>(self->killedUnitCount(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_upgrade_level(bwapi_player_id player_id, int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_upgrade_level")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_upgrade_level");
    if (!self) return 0;
    return static_cast<int32_t>(self->getUpgradeLevel(BWAPI::UpgradeType(upgrade)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_has_researched(bwapi_player_id player_id, int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_has_researched")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_has_researched");
    if (!self) return 0;
    return (self->hasResearched(BWAPI::TechType(tech))) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_researching(bwapi_player_id player_id, int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_researching")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_researching");
    if (!self) return 0;
    return (self->isResearching(BWAPI::TechType(tech))) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_upgrading(bwapi_player_id player_id, int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_upgrading")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_upgrading");
    if (!self) return 0;
    return (self->isUpgrading(BWAPI::UpgradeType(upgrade))) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_color(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::Color(-1).getID(), [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_color")) return BWAPI::Color(-1).getID();
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_color");
    if (!self) return BWAPI::Color(-1).getID();
    return (self->getColor()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_text_color(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_text_color")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_text_color");
    if (!self) return 0;
    return static_cast<int32_t>(self->getTextColor());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_max_energy(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_max_energy")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_max_energy");
    if (!self) return 0;
    return static_cast<int32_t>(self->maxEnergy(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API double BWAPI_C2_CALL bwapi_player_top_speed(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<double>(0.0, [&]() -> double {
    if (!game_ready("bwapi_player_top_speed")) return 0.0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_top_speed");
    if (!self) return 0.0;
    return static_cast<double>(self->topSpeed(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_weapon_max_range(bwapi_player_id player_id, int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_weapon_max_range")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_weapon_max_range");
    if (!self) return 0;
    return static_cast<int32_t>(self->weaponMaxRange(BWAPI::WeaponType(weapon)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_sight_range(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_sight_range")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_sight_range");
    if (!self) return 0;
    return static_cast<int32_t>(self->sightRange(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_weapon_damage_cooldown(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_weapon_damage_cooldown")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_weapon_damage_cooldown");
    if (!self) return 0;
    return static_cast<int32_t>(self->weaponDamageCooldown(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_armor(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_armor")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_armor");
    if (!self) return 0;
    return static_cast<int32_t>(self->armor(BWAPI::UnitType(unit_type)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_damage(bwapi_player_id player_id, int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_damage")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_damage");
    if (!self) return 0;
    return static_cast<int32_t>(self->damage(BWAPI::WeaponType(weapon)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_unit_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_unit_score")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_unit_score");
    if (!self) return 0;
    return static_cast<int32_t>(self->getUnitScore());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_kill_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_kill_score")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_kill_score");
    if (!self) return 0;
    return static_cast<int32_t>(self->getKillScore());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_building_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_building_score")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_building_score");
    if (!self) return 0;
    return static_cast<int32_t>(self->getBuildingScore());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_razing_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_razing_score")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_razing_score");
    if (!self) return 0;
    return static_cast<int32_t>(self->getRazingScore());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_custom_score(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_custom_score")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_custom_score");
    if (!self) return 0;
    return static_cast<int32_t>(self->getCustomScore());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_observer(bwapi_player_id player_id) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_observer")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_observer");
    if (!self) return 0;
    return (self->isObserver()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_get_max_upgrade_level(bwapi_player_id player_id, int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_get_max_upgrade_level")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_get_max_upgrade_level");
    if (!self) return 0;
    return static_cast<int32_t>(self->getMaxUpgradeLevel(BWAPI::UpgradeType(upgrade)));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_research_available(bwapi_player_id player_id, int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_research_available")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_research_available");
    if (!self) return 0;
    return (self->isResearchAvailable(BWAPI::TechType(tech))) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_is_unit_available(bwapi_player_id player_id, int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_is_unit_available")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_is_unit_available");
    if (!self) return 0;
    return (self->isUnitAvailable(BWAPI::UnitType(unit_type))) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_player_has_unit_type_requirement(bwapi_player_id player_id, int32_t unit_type, int32_t amount) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!game_ready("bwapi_player_has_unit_type_requirement")) return 0;
    BWAPI::Player self = resolve_player(player_id, "bwapi_player_has_unit_type_requirement");
    if (!self) return 0;
    return (self->hasUnitTypeRequirement(BWAPI::UnitType(unit_type), amount)) ? 1 : 0;
  });
}

}  // extern "C"
