// GENERATED by tools/abi/emit_source.py from tools/abi/spec/types.yaml; do not edit.
// The boundary every wrapper shares is abi_internal.h; the conversions are docs/spec-format.md
// section 1.4. A change to the ABI is a change to the spec file.
#include "abi_internal.h"

#include <BWAPI/Client.h>
#include <bwem.h>

#include <type_traits>
#include <utility>

using namespace bwapi_c2;

// Every body: and source: entry names the C++ declaration it stands for; these fail the build
// when a pin bump removes or reshapes one (plan section 9).
static_assert(sizeof(&BWAPI::UnitType::whatBuilds) > 0, "spec/types.yaml bwapi_unittype_what_builds: UnitType::whatBuilds not found");
static_assert(sizeof(&BWAPI::UnitType::requiredUnits) > 0, "spec/types.yaml bwapi_unittype_required_units: UnitType::requiredUnits not found");

extern "C" {

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_get_name(int32_t unit_type, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::UnitType(unit_type).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_valid(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_get_race(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::Race(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).getRace()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_what_builds(int32_t unit_type, int32_t* count) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    auto body = [&] {
      auto builder = BWAPI::UnitType(unit_type).whatBuilds();
      if (count) *count = builder.second;
      return builder.first;
    };
    return (body()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_required_units(int32_t unit_type, int32_t* types, int32_t* counts, int32_t cap) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    auto body = [&] {
      if (!check_buffer(types, cap) || !check_buffer(counts, cap)) return 0;
      int32_t total = 0;
      for (const auto& req : BWAPI::UnitType(unit_type).requiredUnits()) {
        if (total < cap) {
          types[total] = req.first.getID();
          counts[total] = req.second;
        }
        ++total;
      }
      return total;
    };
    return static_cast<int32_t>(body());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_required_tech(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::TechType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).requiredTech()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_cloaking_tech(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::TechType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).cloakingTech()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_abilities(int32_t unit_type, int32_t* out, int32_t cap) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    return write_ids(out, cap, BWAPI::UnitType(unit_type).abilities());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_upgrades(int32_t unit_type, int32_t* out, int32_t cap) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    return write_ids(out, cap, BWAPI::UnitType(unit_type).upgrades());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_armor_upgrade(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UpgradeType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).armorUpgrade()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_max_hit_points(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).maxHitPoints());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_max_shields(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).maxShields());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_max_energy(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).maxEnergy());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_armor(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).armor());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_mineral_price(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).mineralPrice());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_gas_price(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).gasPrice());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_build_time(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).buildTime());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_supply_required(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).supplyRequired());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_supply_provided(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).supplyProvided());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_space_required(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).spaceRequired());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_space_provided(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).spaceProvided());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_build_score(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).buildScore());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_destroy_score(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).destroyScore());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_size(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitSizeType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).size()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_tile_width(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).tileWidth());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_tile_height(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).tileHeight());
  });
}

BWAPI_C2_API bwapi_position BWAPI_C2_CALL bwapi_unittype_tile_size(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<bwapi_position>(BWAPI_POSITION_NONE, [&]() -> bwapi_position {
    return pack(BWAPI::UnitType(unit_type).tileSize());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_dimension_left(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).dimensionLeft());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_dimension_up(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).dimensionUp());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_dimension_right(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).dimensionRight());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_dimension_down(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).dimensionDown());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_width(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).width());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_height(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).height());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_seek_range(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).seekRange());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_sight_range(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).sightRange());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_ground_weapon(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::WeaponType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).groundWeapon()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_max_ground_hits(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).maxGroundHits());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_air_weapon(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::WeaponType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).airWeapon()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_max_air_hits(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).maxAirHits());
  });
}

BWAPI_C2_API double BWAPI_C2_CALL bwapi_unittype_top_speed(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<double>(0.0, [&]() -> double {
    return static_cast<double>(BWAPI::UnitType(unit_type).topSpeed());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_acceleration(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).acceleration());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_halt_distance(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).haltDistance());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_turn_radius(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UnitType(unit_type).turnRadius());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_can_produce(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).canProduce()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_can_attack(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).canAttack()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_can_move(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).canMove()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_flyer(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isFlyer()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_regenerates_hp(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).regeneratesHP()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_spellcaster(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isSpellcaster()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_has_permanent_cloak(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).hasPermanentCloak()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_invincible(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isInvincible()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_organic(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isOrganic()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_mechanical(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isMechanical()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_robotic(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isRobotic()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_detector(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isDetector()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_resource_container(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isResourceContainer()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_resource_depot(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isResourceDepot()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_refinery(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isRefinery()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_worker(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isWorker()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_requires_psi(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).requiresPsi()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_requires_creep(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).requiresCreep()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_two_units_in_one_egg(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isTwoUnitsInOneEgg()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_burrowable(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isBurrowable()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_cloakable(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isCloakable()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_building(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isBuilding()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_addon(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isAddon()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_flying_building(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isFlyingBuilding()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_neutral(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isNeutral()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_hero(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isHero()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_powerup(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isPowerup()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_beacon(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isBeacon()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_flag_beacon(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isFlagBeacon()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_special_building(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isSpecialBuilding()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_spell(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isSpell()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_produces_creep(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).producesCreep()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_produces_larva(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).producesLarva()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_mineral_field(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isMineralField()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_critter(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isCritter()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_can_build_addon(int32_t unit_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).canBuildAddon()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_builds_what(int32_t unit_type, int32_t* out, int32_t cap) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    return write_ids(out, cap, BWAPI::UnitType(unit_type).buildsWhat());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_researches_what(int32_t unit_type, int32_t* out, int32_t cap) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    return write_ids(out, cap, BWAPI::UnitType(unit_type).researchesWhat());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_upgrades_what(int32_t unit_type, int32_t* out, int32_t cap) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    return write_ids(out, cap, BWAPI::UnitType(unit_type).upgradesWhat());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unittype_is_successor_of(int32_t unit_type, int32_t type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitType(unit_type).isSuccessorOf(BWAPI::UnitType(type))) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_get_name(int32_t weapon, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::WeaponType(weapon).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_is_valid(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_get_tech(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::TechType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).getTech()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_what_uses(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).whatUses()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_damage_amount(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::WeaponType(weapon).damageAmount());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_damage_bonus(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::WeaponType(weapon).damageBonus());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_damage_cooldown(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::WeaponType(weapon).damageCooldown());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_damage_factor(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::WeaponType(weapon).damageFactor());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_upgrade_type(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UpgradeType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).upgradeType()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_damage_type(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::DamageType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).damageType()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_explosion_type(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::ExplosionType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).explosionType()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_min_range(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::WeaponType(weapon).minRange());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_max_range(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::WeaponType(weapon).maxRange());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_inner_splash_radius(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::WeaponType(weapon).innerSplashRadius());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_median_splash_radius(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::WeaponType(weapon).medianSplashRadius());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_outer_splash_radius(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::WeaponType(weapon).outerSplashRadius());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_targets_air(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).targetsAir()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_targets_ground(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).targetsGround()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_targets_mechanical(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).targetsMechanical()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_targets_organic(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).targetsOrganic()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_targets_non_building(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).targetsNonBuilding()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_targets_non_robotic(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).targetsNonRobotic()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_targets_terrain(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).targetsTerrain()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_targets_org_or_mech(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).targetsOrgOrMech()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_weapontype_targets_own(int32_t weapon) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::WeaponType(weapon).targetsOwn()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_get_name(int32_t tech, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::TechType(tech).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_is_valid(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::TechType(tech).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_get_race(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::Race(-1).getID(), [&]() -> int32_t {
    return (BWAPI::TechType(tech).getRace()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_mineral_price(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::TechType(tech).mineralPrice());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_gas_price(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::TechType(tech).gasPrice());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_research_time(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::TechType(tech).researchTime());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_energy_cost(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::TechType(tech).energyCost());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_what_researches(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::TechType(tech).whatResearches()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_get_weapon(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::WeaponType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::TechType(tech).getWeapon()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_targets_unit(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::TechType(tech).targetsUnit()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_targets_position(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::TechType(tech).targetsPosition()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_what_uses(int32_t tech, int32_t* out, int32_t cap) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    return write_ids(out, cap, BWAPI::TechType(tech).whatUses());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_get_order(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::Order(-1).getID(), [&]() -> int32_t {
    return (BWAPI::TechType(tech).getOrder()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_techtype_required_unit(int32_t tech) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::TechType(tech).requiredUnit()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_get_name(int32_t upgrade, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::UpgradeType(upgrade).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_is_valid(int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UpgradeType(upgrade).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_get_race(int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::Race(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UpgradeType(upgrade).getRace()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_mineral_price(int32_t upgrade, int32_t level) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UpgradeType(upgrade).mineralPrice(level));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_mineral_price_factor(int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UpgradeType(upgrade).mineralPriceFactor());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_gas_price(int32_t upgrade, int32_t level) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UpgradeType(upgrade).gasPrice(level));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_gas_price_factor(int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UpgradeType(upgrade).gasPriceFactor());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_upgrade_time(int32_t upgrade, int32_t level) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UpgradeType(upgrade).upgradeTime(level));
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_upgrade_time_factor(int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UpgradeType(upgrade).upgradeTimeFactor());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_max_repeats(int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::UpgradeType(upgrade).maxRepeats());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_what_upgrades(int32_t upgrade) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UpgradeType(upgrade).whatUpgrades()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_whats_required(int32_t upgrade, int32_t level) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::UpgradeType(upgrade).whatsRequired(level)).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_upgradetype_what_uses(int32_t upgrade, int32_t* out, int32_t cap) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_buffer(out, cap)) return 0;
    return write_ids(out, cap, BWAPI::UpgradeType(upgrade).whatUses());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_race_get_name(int32_t race, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::Race(race).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_race_is_valid(int32_t race) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::Race(race).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_race_get_worker(int32_t race) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::Race(race).getWorker()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_race_get_resource_depot(int32_t race) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::Race(race).getResourceDepot()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_race_get_refinery(int32_t race) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::Race(race).getRefinery()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_race_get_transport(int32_t race) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::Race(race).getTransport()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_race_get_supply_provider(int32_t race) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(BWAPI::UnitType(-1).getID(), [&]() -> int32_t {
    return (BWAPI::Race(race).getSupplyProvider()).getID();
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unitsizetype_get_name(int32_t size, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::UnitSizeType(size).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unitsizetype_is_valid(int32_t size) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitSizeType(size).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_damagetype_get_name(int32_t damage, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::DamageType(damage).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_damagetype_is_valid(int32_t damage) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::DamageType(damage).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_explosiontype_get_name(int32_t explosion, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::ExplosionType(explosion).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_explosiontype_is_valid(int32_t explosion) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::ExplosionType(explosion).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_bullettype_get_name(int32_t bullet, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::BulletType(bullet).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_bullettype_is_valid(int32_t bullet) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::BulletType(bullet).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_order_get_name(int32_t order, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::Order(order).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_order_is_valid(int32_t order) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::Order(order).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_playertype_get_name(int32_t player_type, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::PlayerType(player_type).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_playertype_is_valid(int32_t player_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::PlayerType(player_type).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_playertype_is_lobby_type(int32_t player_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::PlayerType(player_type).isLobbyType()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_playertype_is_game_type(int32_t player_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::PlayerType(player_type).isGameType()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_gametype_get_name(int32_t game_type, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::GameType(game_type).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_gametype_is_valid(int32_t game_type) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::GameType(game_type).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unitcommandtype_get_name(int32_t command, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::UnitCommandType(command).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_unitcommandtype_is_valid(int32_t command) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::UnitCommandType(command).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_error_get_name(int32_t error, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::Error(error).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_error_is_valid(int32_t error) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::Error(error).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_color_get_name(int32_t color, char* buf, int32_t buf_len) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    if (!check_string_buffer(buf, buf_len)) return 0;
    empty_string(buf, buf_len);
    return write_string(buf, buf_len, BWAPI::Color(color).getName());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_color_is_valid(int32_t color) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return (BWAPI::Color(color).isValid()) ? 1 : 0;
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_color_red(int32_t color) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::Color(color).red());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_color_green(int32_t color) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::Color(color).green());
  });
}

BWAPI_C2_API int32_t BWAPI_C2_CALL bwapi_color_blue(int32_t color) BWAPI_C2_NOEXCEPT {
  return guard<int32_t>(0, [&]() -> int32_t {
    return static_cast<int32_t>(BWAPI::Color(color).blue());
  });
}

}  // extern "C"
